return {
  'nvim-treesitter/nvim-treesitter',
  version = false,
  build = ':TSUpdate',
  event = { 'BufReadPost', 'BufNewFile' },
  opts = {
    ensure_installed = {
      'yaml',
      'json',
      'c',
      'lua',
      'luadoc',
      'asm',
      'vim',
      'cpp',
      'rust',
      'python',
      'json',
      'yaml',
      'toml',
      'bash',
      'fish',
      'awk',
      'kdl',
      'dosini',
      'diff',
      'cmake',
      'git_config',
      'gitignore',
      'gitcommit',
      'git_rebase',
      'gitattributes',
      'astro',
      'html',
      'css',
      'vim',
      'vimdoc',
      'typst',
      'latex',
      'go',
      'glsl',
      'llvm',
      'ninja',
      'markdown',
      'markdown_inline',
      'qmljs',
      'norg'
    }
  },
  config = function(_, opts)
    require('nvim-treesitter').setup { install_dir = vim.fn.stdpath 'data' .. '/site' }
    require('nvim-treesitter').install(opts.ensure_installed)
  end,
}
